# Copyright (c) 2026-present matstech
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# SPDX-License-Identifier: MIT

"""Canonical type tags and public payload keys for DMF data contracts."""

from __future__ import annotations

UNKNOWN_VALUE = "unknown"

CARD_KIND_FACT = "fact"
CARD_KIND_PREFERENCE = "preference"
CARD_KIND_CURRENT_STATE = "current_state"
CARD_KIND_EVENT = "event"
CARD_KIND_RELATION = "relation"
CARD_KIND_CONSTRAINT = "constraint"
CARD_KIND_CORRECTION = "correction"
VALID_CARD_KINDS = frozenset({
    CARD_KIND_FACT,
    CARD_KIND_PREFERENCE,
    CARD_KIND_CURRENT_STATE,
    CARD_KIND_EVENT,
    CARD_KIND_RELATION,
    CARD_KIND_CONSTRAINT,
    CARD_KIND_CORRECTION,
})

CARD_STATUS_ACTIVE = "active"
CARD_STATUS_SUPERSEDED = "superseded"
CARD_STATUS_INVALIDATED = "invalidated"
CARD_STATUS_CORRECTED = "corrected"
VALID_CARD_STATUSES = frozenset({
    CARD_STATUS_ACTIVE,
    CARD_STATUS_SUPERSEDED,
    CARD_STATUS_INVALIDATED,
    CARD_STATUS_CORRECTED,
})
STALE_CARD_STATUSES = frozenset({
    CARD_STATUS_SUPERSEDED,
    CARD_STATUS_INVALIDATED,
    CARD_STATUS_CORRECTED,
})

QUERY_ANSWER_TYPE_BOOLEAN = "boolean"
QUERY_ANSWER_TYPE_FACT = "fact"
QUERY_ANSWER_TYPE_LIST = "list"
QUERY_ANSWER_TYPE_PERSON = "person"
QUERY_ANSWER_TYPE_PLACE = "place"
QUERY_ANSWER_TYPE_QUANTITY = "quantity"
QUERY_ANSWER_TYPE_REASON = "reason"
QUERY_ANSWER_TYPE_TIME = "time"
QUERY_ANSWER_TYPE_UNKNOWN = UNKNOWN_VALUE
VALID_QUERY_ANSWER_TYPES = frozenset({
    QUERY_ANSWER_TYPE_BOOLEAN,
    QUERY_ANSWER_TYPE_FACT,
    QUERY_ANSWER_TYPE_LIST,
    QUERY_ANSWER_TYPE_PERSON,
    QUERY_ANSWER_TYPE_PLACE,
    QUERY_ANSWER_TYPE_QUANTITY,
    QUERY_ANSWER_TYPE_REASON,
    QUERY_ANSWER_TYPE_TIME,
    QUERY_ANSWER_TYPE_UNKNOWN,
})

QUERY_TEMPORAL_CURRENT = "current"
QUERY_TEMPORAL_HISTORICAL = "historical"
QUERY_TEMPORAL_LATEST = "latest"
QUERY_TEMPORAL_NONE = "none"
QUERY_TEMPORAL_RANGE = "temporal_range"
VALID_QUERY_TEMPORAL_INTENTS = frozenset({
    QUERY_TEMPORAL_CURRENT,
    QUERY_TEMPORAL_HISTORICAL,
    QUERY_TEMPORAL_LATEST,
    QUERY_TEMPORAL_NONE,
    QUERY_TEMPORAL_RANGE,
})

QUERY_CURRENTNESS_CURRENT = "current"
QUERY_CURRENTNESS_HISTORICAL = "historical"
QUERY_CURRENTNESS_MIXED = "mixed"
QUERY_CURRENTNESS_UNSPECIFIED = "unspecified"
VALID_QUERY_CURRENTNESS = frozenset({
    QUERY_CURRENTNESS_CURRENT,
    QUERY_CURRENTNESS_HISTORICAL,
    QUERY_CURRENTNESS_MIXED,
    QUERY_CURRENTNESS_UNSPECIFIED,
})

QUERY_POLARITY_NEGATIVE = "negative"
QUERY_POLARITY_POSITIVE = "positive"
VALID_QUERY_POLARITIES = frozenset({
    QUERY_POLARITY_NEGATIVE,
    QUERY_POLARITY_POSITIVE,
})

EVIDENCE_TYPE_CARD = "card"
EVIDENCE_TYPE_RAW_TURN = "raw_turn"
EVIDENCE_TYPE_CARD_BACKED_TURN = "card_backed_turn"
VALID_EVIDENCE_TYPES = frozenset({
    EVIDENCE_TYPE_CARD,
    EVIDENCE_TYPE_RAW_TURN,
    EVIDENCE_TYPE_CARD_BACKED_TURN,
})

FIELD_CARD_ID = "card_id"
FIELD_RECORD_ID = "record_id"
FIELD_SOURCE_RECORD_ID = "source_record_id"
FIELD_SPEAKER_ROLE = "speaker_role"
FIELD_SOURCE_TURN = "source_turn"
FIELD_VALIDITY = "validity"
FIELD_VALIDITY_STATUS = "validity_status"
FIELD_PROVENANCE = "provenance"
FIELD_SURFACE_FORMS = "surface_forms"
FIELD_RENDER_PAYLOAD = "render_payload"
