"""Shared constants for configuration, storage backends, and runtime units."""

from __future__ import annotations

from pathlib import Path

DEFAULT_TEXT_ENCODING = "utf-8"
SECONDS_TO_MILLISECONDS = 1000.0

DEFAULT_SETTINGS_FILENAME = "dmf_settings.toml"
DEFAULT_SETTINGS_PATH = Path(__file__).resolve().parents[2] / DEFAULT_SETTINGS_FILENAME

DEFAULT_SPACY_MODEL = "en_core_web_sm"
DEFAULT_EMBEDDING_MODEL = "nomic-ai/nomic-embed-text-v1.5"
DEFAULT_VECTOR_DIM = 768
DEFAULT_EMBEDDING_CACHE_DIR = "models/embeddings"
DEFAULT_WINDOW_SIZE = 10

DEFAULT_SCORING_ALPHA_DENSITY = 3.0
DEFAULT_SCORING_BETA_ENTITIES = 2.0
DEFAULT_SCORING_GAMMA_SENTIMENT = 1.5
DEFAULT_SCORING_DELTA_TECHNICAL = -1.5
DEFAULT_SCORING_SIGMOID_MIDPOINT = 1.5
DEFAULT_SCORING_ENTITY_CAP = 5
DEFAULT_SCORING_SOCIAL_THRESHOLD = 0.4
DEFAULT_SCORING_MIN_SOCIAL_SCORE = 0.25
DEFAULT_SCORING_LAMBDA_OPERATIONAL = 0.75
DEFAULT_SCORING_ETA_CONSTRAINT = 1.2
DEFAULT_SCORING_ETA_PREFERENCE = 0.7
DEFAULT_SCORING_ETA_CURRENT_STATE = 0.6
DEFAULT_SCORING_ETA_CORRECTION = 0.9
DEFAULT_SCORING_ETA_REPLACEMENT = 0.5
DEFAULT_SCORING_ETA_PAST_STATE = 0.0
DEFAULT_SCORING_USER_CORRECTION_BOOST = 0.0
DEFAULT_SCORING_PREFERENCE_UPDATE_BOOST = 0.0
DEFAULT_SCORING_CONSTRAINT_BOOST = 0.0
DEFAULT_SCORING_CORRECTED_BY_USER_PENALTY = 0.0

DEFAULT_DECAY_LAMBDA_BASE = 0.035
DEFAULT_DECAY_INERTIA_STRENGTH = 0.5
DEFAULT_DECAY_HARD_KILL_THRESHOLD = 0.05

DEFAULT_TIER_CRITICAL_MAX = 0.3
DEFAULT_TIER_UNSTABLE_MAX = 0.6
DEFAULT_TIER_HEALTHY_MIN = 0.6

DEFAULT_TOKEN_BUDGET = 4096
DEFAULT_PRUNING_FREQUENCY = 5

DEFAULT_PRUNING_RHO_CONSTRAINT = 0.2
DEFAULT_PRUNING_RHO_PREFERENCE = 0.1
DEFAULT_PRUNING_RHO_CURRENT_STATE = 0.1
DEFAULT_PRUNING_RHO_CORRECTION = 0.15
DEFAULT_PRUNING_RHO_REPLACEMENT = 0.08
DEFAULT_PRUNING_SUPERSEDED_PAST_PENALTY = 0.35

LTM_BACKEND_FILE = "file"
LTM_BACKEND_CHROMA = "chroma"
LTM_BACKEND_NULL = "null"
SUPPORTED_LTM_BACKENDS = frozenset({
    LTM_BACKEND_FILE,
    LTM_BACKEND_CHROMA,
    LTM_BACKEND_NULL,
})

DEFAULT_LTM_STORAGE_PATH = "data/ltm_archive.jsonl"
DEFAULT_LTM_CHROMA_PATH = "data/ltm_chroma"
DEFAULT_LTM_COLLECTION_NAME = "dmf_memory"
DEFAULT_LTM_RECALL_LIMIT = 5
DEFAULT_LTM_DISTANCE_THRESHOLD = 0.7
DEFAULT_LTM_CARDS_PATH = "data/ltm_cards.jsonl"
DEFAULT_LTM_CARDS_COLLECTION_NAME = "dmf_cards"

DEFAULT_RETRIEVAL_CARD_PREFETCH_K = 32
DEFAULT_RETRIEVAL_RAW_PREFETCH_K = 16
DEFAULT_RETRIEVAL_SYMBOLIC_LOOKUP_K = 16
DEFAULT_RETRIEVAL_FINAL_RECALL_LIMIT = 5
DEFAULT_RETRIEVAL_MAX_SUPPORT_TURNS_PER_CARD = 3
